name: CI - FastAPI LLM API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t nda-conflict-api .

    - name: Run container and test API health
      run: |
        docker run -d -p 8000:8000 nda-conflict-api
        sleep 10  # Give container time to start
        curl --fail http://localhost:8000/docs || exit 1

    - name: Push image to Docker Hub
      run: docker tag nda-conflict-api ${{ secrets.DOCKERHUB_USERNAME }}/nda-conflict-api:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/nda-conflict-api:latest
